### ISSUE TITLE
Move the markdown pages to the root URL

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/glowstonemc.github.io#1]
Pages rendered based on Markdown (e.g. https://glowstonemc.github.io/pages/cla) need to be moved to the root URL (https://glowstonemc.github.io/cla).

Should just be a matter of updating `PAGE_URL = 'pages/{slug}'`. See https://docs.getpelican.com/en/latest/content.html#pages

**Comment by mastercoms** [comment]
https://docs.getpelican.com/en/latest/settings.html?highlight=PAGE_PATHS#url-settings
